version: 2.1

jobs:
  build:
    working_directory: ~/company-parking-spot

    docker:
      - image: cimg/openjdk:21.0.0

    steps:
      - checkout

      - restore_cache:
          paths:
            - ~/.m2
          key: company-parking-spot-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: company-parking-spot-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/company-parking-spot-0.0.1-SNAPSHOT.jar

workflows:
  main:
    jobs:
      - build